export const NIGERIAN_DENOMINATIONS = [
  'Assemblies of God Nigeria',
  'The Apostolic Church Nigeria',
  'Baptist Convention (Nigerian Baptist Convention)',
  'Catholic Church in Nigeria',
  'Christ Embassy (Believers\' LoveWorld)',
  'Celestial Church of Christ (CCC)',
  'Christ Apostolic Church (CAC)',
  'Deeper Christian Life Ministry',
  'Daystar Christian Centre',
  'Dunamis International Gospel Centre',
  'Evangelical Church Winning All (ECWA)',
  'Foursquare Gospel Church in Nigeria',
  'The Fountain of Life Church',
  'Gospel Faith Mission International (GOFAMINT)',
  'House on the Rock',
  'INRI Evangelical Spiritual Church',
  'Jehovah\'s Witnesses Nigeria',
  'Jesus Reign Ministries',
  'Kingsway International Christian Centre (KICC Nigeria)',
  'Living Faith Church Worldwide (Winners\' Chapel)',
  'The Lord\'s Chosen Charismatic Revival Movement',
  'Methodist Church Nigeria',
  'Mountain of Fire and Miracles Ministries (MFM)',
  'New Apostolic Church Nigeria',
  'Omega Fire Ministries International',
  'Omega Power Ministries (OPM)',
  'Pentecostal / Charismatic (General)',
  'Presbyterian Church of Nigeria',
  'Redeemed Christian Church of God (RCCG)',
  'Salvation Ministries',
  'The Salvation Army Nigeria',
  'The Redeemed Evangelical Mission (TREM)',
  'The Anglican Church of Nigeria',
  'United Methodist Church Nigeria',
  'Victory Life Bible Church',
  'Word of Life Bible Church',
  'Yaba Baptist Church',
  'Zion Ministry (Ebube Muonso)',
  'Other'
];
