import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js');
importScripts('https://www.gstatic.com/firebasejs/8.10.1/firebase-messaging.js');

// Initialize the Firebase app in the service worker
// We use the older v8 syntax here because importScripts doesn't support ES modules out of the box in all browsers
firebase.initializeApp({
  apiKey: "AIzaSyBY57-IZWhGnS0BzvKpji5OE-epMqGv8EI",
  authDomain: "church-match-0101.firebaseapp.com",
  projectId: "church-match-0101",
  storageBucket: "church-match-0101.firebasestorage.app",
  messagingSenderId: "13169289051",
  appId: "1:13169289051:web:72ac5ac33526bda1ef9c7e"
});

const messaging = firebase.messaging();

// Handle background messages
messaging.onBackgroundMessage(function(payload) {
  console.log('[firebase-messaging-sw.js] Received background message ', payload);

  const notificationTitle = payload.notification.title;
  const notificationOptions = {
    body: payload.notification.body,
    icon: '/church-logo.png', // Assuming there's a logo in public folder
    badge: '/church-logo.png',
    data: payload.data
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle clicking the notification to open the app
self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  // Try to open the chat window, or focus it if it's already open
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then(windowClients => {
      const urlToOpen = event.notification.data?.url || '/app/chat';
      
      for (var i = 0; i < windowClients.length; i++) {
        var client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
